development:
  adapter: postgresql
  encoding: utf8
  database: cubetimes_development
  pool: 100
  timeout: 5000
  password:
  host:

test:
  adapter: postgresql
  encoding: utf8
  database: cubetimes_test
  pool: 5
  timeout: 5000
  password:
  host:

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: utf8
  pool: 5

default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
